# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      locations: ${{ steps.get_resource_location.outputs.locations }}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: RunPS - Get resource locations
        id: get_resource_location
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $locationList = "uksouth"
            echo locations=$locationList >> $GITHUB_OUTPUT
            echo *** List of Locations*** $locationList
          azPSVersion: "latest"
          
      # Reformat PowerShell output to JSON and put in matrix
      - name: Format Json
        id: set_location_matrix
        run: |
          echo Before restructure --- ${{ steps.get_resource_location.outputs.locations }}
          
