# This is a basic workflow to help you get started with Actions

name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      locations: ${{ steps.get_resource_location.outputs.locations }}
      
    steps:
      - uses: actions/checkout@v3

      - name: RunPS - Get resource locations
        id: get_resource_location
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $locationList = "uksouth"
            write-output locations=$locationList >> $GITHUB_OUTPUT
            write-output "*** List of Locations*** $locationList"
          azPSVersion: "latest"
          
      - name: Format Json
        id: set_location_matrix
        run: |
          write-output "Before restructure --- ${{ steps.get_resource_location.outputs.locations }}"
          
