# This is a basic workflow to help you get started with Actions

name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      locations: ${{ steps.get_resource_location.outputs.locations }}
      
    steps:
      - uses: actions/checkout@v3

#       - name: RunPS - Get resource locations
#         id: get_resource_location
#         uses: azure/powershell@v1
#         with:
#           inlineScript: |
#             $locationList = "uksouth"
#             write-output locations=$locationList >> $GITHUB_OUTPUT
#             write-output "*** List of Locations*** $locationList"
#           azPSVersion: "latest"
     
      - name: RunPS - Get resource locations
        id: get_resource_location
        run: |
            locationList=['uksouth' 'northeurope']
            echo locations=$locationList >> $GITHUB_OUTPUT
            echo "*** List of Locations*** $locationList"
          
     
      - name: Format Json
        id: set_location_matrix
        run: |
          echo "Before restructure --- ${{ steps.get_resource_location.outputs.locations }}"
          JSON="$( printf %s\\n ${{ steps.get_resource_location.outputs.locations }} | jq -R .|jq -s .)"
          echo "matrix=$JSON" >> $GITHUB_OUTPUT
          echo After restructure --- $JSON
